from typing import Any, Dict, List, Optional
from pydantic import Field

from src.state import StateModel
from src.scout.model import PlanModel


class ScoutState(StateModel):
    objective: str = Field(description="The strategic objective for the scout agent.", default="")
    plan: Optional[PlanModel] = Field(
        default=None,
        description="Structured multi-phase plan generated by the planner agent.",
    )
    memory: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Rolling structured memory entries captured during the operation.",
    )
